### ISSUE TITLE
roadmap for 2.3.12

### ISSUE THREAD

**Issue by sthalik** [opentrack/opentrack#1051]
Roadmap:

- [x] update LibOVR
- [x] add prototype ps3eye open driver
- [x] fix vjoystick
- [x] update RealSense SDK to R3
- [x] maybe fix Kinect video source bug

**Comment by omegatao** [comment]
how about adding support for Nintendo Switch Joy-Con as an input device?

**Comment by sthalik** [comment]
@omegatao not unless someone contributes the code.

**Comment by Need4SpeedOG** [comment]
RealSense SDK is now open sourced at 2.0 also on GitHub https://github.com/IntelRealSense/librealsense don't know if this would be a major retooling

**Comment by sthalik** [comment]
The open-source version is missing face-tracking. It can't be used.

**Comment by sthalik** [comment]
> Is there anything that can be done to make SteamVR + Vive tracker without an HMD work?

Only if steamvr allows it.

**Comment by PhilWilliams-dev** [comment]
> > Is there anything that can be done to make SteamVR + Vive tracker without an HMD work?
> 
> Only if steamvr allows it.

What's interesting is that there is a way to fire up steamVR without the HMD by using the 'null' driver which works, I get green tracking stations and the Vive tracker but for some reason Opentrack does not receive any tracking data unless the physical HMD is connected...

**Comment by sthalik** [comment]
I'm almost ready to release a ps3eye open driver build. If you want to test it, please:

- Install `libusbK.sys` as the driver for the camera, by youself (without me providing instructions).
- Reply in this issue.

**Comment by sthalik** [comment]
FWIW, I'm so happy with the state of the driver that I might just as well push a release candidate. The CPU usage on Windows is very minimal.

**Comment by wostg** [comment]
Hey fella, it occurred to me while I'm throwing money around (1 week till FS2020 lol) I should support software that will get equivalent use. (kinect working great on the fs beta). I saw the note about supporting the EFF but if you or other significant contribs have one of those 'buy me a coffee' deals, or other currently preferred charities please do say.

**Comment by wostg** [comment]
And you Slion! 👍
